name: Kora LED
favicon: null
layout_spectrum: 0.13709
typography_spectrum: 0.47323
title: Kora LED - Professional quality LED lights for film and TV at indie-friendly prices
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6526265693828464
  lightness: 0
  saturation: 0.36261508241295815
  rhythmicContrast: 0.10249565541744232
purpose: []
